"""Build a coherent labelled subsample of the real training data.

Sampling Source 2/3 rows independently of Source 1 does not work: the true
matches of a sampled entity are scattered across 10M rows, so a naive
subsample contains almost no positives and the F_0.5 it produces measures the
sampler rather than the pipeline.

This builds a subsample with the class structure intact:

  * N Source 1 entities, sampled at random;
  * **every** Source 2/3 record the ground truth says matches one of them -- the
    positives;
  * a random sample of the remaining Source 2/3 records -- the negatives, drawn
    from the same files and therefore carrying the same noise (abbreviations,
    transliterations, dropped components) as the positives.

It also writes a `config` YAML pointing at the subsample, so the pipeline runs
against it with `--er-config` and nothing else to remember.
"""

from __future__ import annotations

import argparse
import os
import sys
import time
from typing import Dict, List, Set

import numpy as np
import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.metrics import load_ground_truth

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "student_resource", "dataset", "train")

CONFIG_TEMPLATE = """\
# Auto-generated by tools/build_er_subsample.py -- a dev config, not for scoring.
version: 1
sep: "\\t"
chunk_size: {chunk_size}
max_training_pairs: {max_training_pairs}
max_tuning_pairs: 1000000
max_rollup_pairs: 20000000

paths:
  validate:
    source1: {out}/source1.tsv
    source2: {out}/source2.tsv
    source3: {out}/source3.tsv
    ground_truth: {out}/ground_truth.tsv
  predict:
    source1: {out}/source1.tsv
    source2: {out}/source2.tsv
    source3: {out}/source3.tsv

sources:
  source1:
    id_col: entity_id
    fields: {{name: business_name, address: business_address, country: country}}
  source2:
    id_col: entity_id
    fields: {{name: business_name, address: business_address, country: country}}
  source3:
    id_col: entity_id
    fields: {{name: business_name, address: business_address, country: country}}

blocking:
  max_candidates_per_record: 100
  per_rule_cap: 40
  large_candidate_multiplier: 2.0
  name_prefix_len: 4
  phonetic_scheme: nysiis
  min_token_len: 3
  max_bucket_size: 400
  # Keep the df cutoff at or below the bucket cap (see config/er.yaml).
  max_token_df_ratio: 0.01
  max_token_df_absolute: {max_token_df_absolute}
  scope_token_index_by_country: true
  enable_country_prefix: true
  enable_country_city_prefix: true
  enable_shared_token: true
  enable_phonetic_country: true
  enable_exact_entity_id: false
  enable_fallback: true
  fallback_fuzzy_floor: 0.72
  fallback_window: 15
  fallback_neighborhood_window: 3
  fallback_max_candidates: 50
  enable_debug_log: true
  max_debug_rows: 200000

weights:
  name: 0.45
  address: 0.30
  city_state: 0.15
  country: 0.10

decision:
  high_threshold: 0.85
  low_threshold_ratio: 0.60
  low_threshold: null
  ambiguity_margin: 0.05
  block_on_country_conflict: true
  block_on_location_conflict: true
  location_conflict_floor: 0.80

validation:
  val_fraction: 0.20
  tune_fraction: 0.50

model:
  prefer: lightgbm
  n_estimators: 400
  learning_rate: 0.06
  max_leaf_nodes: 31
  min_samples_leaf: 20
  n_jobs: 8
"""


def _read(path: str) -> pd.DataFrame:
    return pd.read_csv(path, sep="\t", dtype=str, keep_default_na=False, na_values=[])


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--n-s1", type=int, default=20000,
                    help="Source 1 entities to keep")
    ap.add_argument("--n-neg", type=int, default=200000,
                    help="non-matching Source 2/3 records to keep, split evenly")
    ap.add_argument("--out", default="artifacts/er_subsample")
    ap.add_argument("--chunk-size", type=int, default=20000)
    ap.add_argument("--max-training-pairs", type=int, default=400000)
    ap.add_argument("--seed", type=int, default=0)
    args = ap.parse_args()
    os.makedirs(args.out, exist_ok=True)

    rng = np.random.default_rng(args.seed)
    t0 = time.time()

    print("reading ground truth ...")
    truth: Dict[str, Set[str]] = load_ground_truth(
        os.path.join(DATA, "train_ground_truth.tsv")
    )[0]
    print(f"  {len(truth):,} entities, "
          f"{sum(len(v) for v in truth.values()):,} true matches "
          f"({time.time() - t0:.0f}s)")

    keys = sorted(truth)
    keep_idx = np.sort(rng.choice(len(keys), min(args.n_s1, len(keys)), replace=False))
    s1_ids = [keys[i] for i in keep_idx]
    s1_id_set = set(s1_ids)

    want: Set[str] = set()
    for eid in s1_ids:
        want |= truth[eid]
    print(f"sampled {len(s1_ids):,} Source 1 entities -> {len(want):,} true matches")

    s1 = _read(os.path.join(DATA, "train_source1.tsv"))
    s1 = s1[s1["entity_id"].isin(s1_id_set)].reset_index(drop=True)
    s1.to_csv(os.path.join(args.out, "source1.tsv"), sep="\t", index=False)
    print(f"  source1: {len(s1):,} rows")

    per_source_neg = max(0, args.n_neg // 2)
    for src in (2, 3):
        df = _read(os.path.join(DATA, f"train_source{src}.tsv"))
        pos = df[df["entity_id"].isin(want)]
        rest = df[~df["entity_id"].isin(want)]
        take = min(per_source_neg, len(rest))
        neg = rest.iloc[rng.choice(len(rest), take, replace=False)]
        out = pd.concat([pos, neg], ignore_index=True)
        out.to_csv(os.path.join(args.out, f"source{src}.tsv"), sep="\t", index=False)
        print(f"  source{src}: {len(pos):,} positives + {len(neg):,} negatives")

    # Ground truth restricted to the sampled entities -- including the rows with
    # an empty match list, because the macro average is over every entity and
    # dropping the singletons would inflate the score.
    with open(os.path.join(args.out, "ground_truth.tsv"), "w") as fh:
        fh.write("source1_entity_id\tmatched_entity_ids\n")
        for eid in s1_ids:
            fh.write(f"{eid}\t{','.join(sorted(truth[eid]))}\n")

    cfg_path = os.path.join(args.out, "er_subsample.yaml")
    with open(cfg_path, "w") as fh:
        fh.write(CONFIG_TEMPLATE.format(
            out=args.out, chunk_size=args.chunk_size,
            max_training_pairs=args.max_training_pairs,
            n_s1=len(s1_ids),
            # On a subsample the ratio alone would be a tiny number, so the
            # absolute floor is what actually binds; 400 mirrors the bucket cap
            # used in config/er.yaml, which is the measured knee.
            max_token_df_absolute=400,
        ))
    print(f"\nwrote {args.out}/ and {cfg_path}")
    print("run it with:\n"
          f"  .venv/bin/python run_pipeline.py --mode er --er-config {cfg_path} "
          f"--out-dir {args.out}/out --work-dir {args.out}/work")
    return 0


if __name__ == "__main__":
    sys.exit(main())
